# from: https://kubernetes.io/docs/concepts/storage/storage-classes/#aws-ebs
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "10"
  fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fiobench-pv
  namespace: mercado
  labels:
    fiobench: image
    deployment: test
    subject: separated-workload-from-volume
spec:
  storageClassName: longhorn-static
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  csi:
    driver: # ebs
    fsType: ext4
    volumeAttributes:
      # ???
    volumeHandle: fiobench-vol # refers to volume on node
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fiobench-pvc
  namespace: mercado
  labels:
    fiobench: image
    deployment: test
    subject: separated-workload-from-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
  volumeName: fiobench-pv
  storageClassName: longhorn-static
  selector:
    matchLabels:
      fiobench: image
      deployment: test
      subject: separated-workload-from-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiobench-deployment
  namespace: mercado
  labels:
    fiobench: image
    deployment: test
    subject: separated-workload-from-volume
spec:
  replicas: 1
  selector:
    matchLabels:
      fiobench: image
      deployment: test
      subject: separated-workload-from-volume
  template:
    metadata:
      labels:
        fiobench: image
        deployment: test
        subject: separated-workload-from-volume
    spec:
      containers:
      - name: fiobench
        image: ghcr.io/pabloheigvd/tb-fiobench:latest
#        command: [ "/bin/sh", "run-all-jobs.sh" ] # TODO uncomment and run jobs
        volumeMounts:
          - name: fiobench-storage
            mountPath: /data
      nodeSelector:
        kubernetes.io/hostname: "10.193.72.32"
      volumes:
        - name: fiobench-storage
          persistentVolumeClaim:
            claimName: fiobench-pvc
