apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-ebs-storage-class
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fiobench-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
  storageClassName: gp2-ebs-storage-class
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiobench-deployment
  labels:
    fiobench: image
    deployment: test
    subject: separated-workload-from-volume
spec:
  replicas: 1
  selector:
    matchLabels:
      fiobench: image
      deployment: test
      subject: separated-workload-from-volume
  template:
    metadata:
      labels:
        fiobench: image
        deployment: test
        subject: separated-workload-from-volume
    spec:
      containers:
      - name: fiobench
        image: ghcr.io/pabloheigvd/tb-fiobench:latest
        command: [ "/bin/sh", "run-all-jobs.sh" ]
        volumeMounts:
          - name: fiobench-storage
            mountPath: /data
      volumes:
        - name: fiobench-storage
          persistentVolumeClaim:
            claimName: fiobench-pvc
