# inspired from: https://raw.githubusercontent.com/mahaupt/fiobench/master/fiobench.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fiobench-longhorn-pvc
  namespace: mercado
  labels:
    deployment: "00"
    fiobench: manual
    subject: manual
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
---
# inspired from: https://raw.githubusercontent.com/kubernetes/website/main/content/fr/examples/controllers/nginx-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiobench-deployment
  namespace: mercado
  labels:
    deployment: "00"
    fiobench: manual
    subject: manual
spec:
  replicas: 1
  selector:
    matchLabels:
      fiobench: manual
  template:
    metadata:
      labels:
        deployment: "00"
        fiobench: manual
        subject: manual
    spec:
      containers:
        - name: fiobench
          image: ghcr.io/pabloheigvd/tb-fiobench:latest
          # clever hack to keep pod running: https://stackoverflow.com/a/40093356
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          volumeMounts:
            - name: test-volume
              mountPath: /data
      volumes:
        - name: test-volume
          persistentVolumeClaim:
            claimName: fiobench-longhorn-pvc
