apiVersion: v1
kind: PersistentVolume
metadata:
  name: longhorn-test-pv
  labels:
    bench: image
    deployment: "07"
    subject: local-no-replica
spec:
  capacity:
    storage: 1000Gi
  accessModes:
  - ReadWriteOnce
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "0" # FIXME 3 replicas dans l'ui rancher
      size: 1000Gi
      staleReplicaTimeout: "2880"
    volumeHandle: "longhorn-test-pv"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "10.193.72.32"
---
# inspired from: https://raw.githubusercontent.com/mahaupt/fiobench/master/fiobench.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fiobench-longhorn-pvc
  namespace: mercado
  labels:
    bench: image
    deployment: "07"
    subject: local-no-replica
spec:
  storageClassName: longhorn-test-pv
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1000Gi
---
# inspired from: https://raw.githubusercontent.com/kubernetes/website/main/content/fr/examples/controllers/nginx-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiobench
  namespace: mercado
  labels:
    fiobench: image
    deployment: "07"
    subject: local-no-replica
spec:
  replicas: 1
  selector:
    matchLabels:
      fiobench: image
  template:
    metadata:
      labels:
        fiobench: image
        deployment: "07"
        subject: local-no-replica
    spec:
      nodeSelector:
        kubernetes.io/hostname: "10.193.72.32"
      containers:
        - name: fiobench
          image: ghcr.io/pabloheigvd/tb-fiobench:latest
          command: [ "/bin/sh", "run-all-jobs.sh" ]
          volumeMounts:
            - name: test-volume
              mountPath: /data
      volumes:
        - name: test-volume
          persistentVolumeClaim:
            claimName: fiobench-longhorn-pvc
