kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-test
  namespace: mercado
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "0"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: longhorn-test-pv
spec:
  capacity:
    storage: 1000Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-test
  local:
    path: /data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "10.193.72.32"
---
# inspired from: https://raw.githubusercontent.com/mahaupt/fiobench/master/fiobench.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fiobench-longhorn-pvc
  namespace: mercado
  labels:
    bench: image
    deployment: "07"
    subject: local-no-replica
spec:
  storageClassName: longhorn-test
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1000Gi
---
# inspired from: https://raw.githubusercontent.com/kubernetes/website/main/content/fr/examples/controllers/nginx-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiobench
  namespace: mercado
  labels:
    fiobench: image
    deployment: "07"
    subject: local-no-replica
spec:
  replicas: 1
  selector:
    matchLabels:
      fiobench: image
  template:
    metadata:
      labels:
        fiobench: image
        deployment: "07"
        subject: local-no-replica
    spec:
      nodeSelector:
        kubernetes.io/hostname: "10.193.72.32"
      containers:
        - name: fiobench
          image: ghcr.io/pabloheigvd/tb-fiobench:latest
          command: [ "/bin/sh", "run-all-jobs.sh" ]
          volumeMounts:
            - name: test-volume
              mountPath: /
      volumes:
        - name: test-volume
          persistentVolumeClaim:
            claimName: fiobench-longhorn-pvc
