# kubectl describe pod -n mercado
# Events:
#  Type     Reason       Age   From               Message
#  ----     ------       ----  ----               -------
#  Normal   Scheduled    3m5s  default-scheduler  Successfully assigned mercado/fiobench-deployment-5fb794bdfd-thrkf to 10.193.72.32
#  Warning  FailedMount  61s   kubelet            Unable to attach or mount volumes: unmounted volumes=[fiobench-storage], unattached volumes=[fiobench-storage default-token-j452w]: timed out waiting for the condition

apiVersion: v1
kind: PersistentVolume
metadata:
  name: fiobench-pv
  namespace: mercado
  labels:
    fiobench: image
    deployment: "07"
    subject: local-no-replica
spec:
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  csi:
    driver: io.rancher.longhorn
    fsType: ext4
    volumeAttributes:
      numberOfReplicates: '0'
      staleReplicaTimeout: '2880'
    volumeHandle: fiobench-volume-handle
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - "10.193.72.32"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fiobench-pvc
  namespace: mercado
  labels:
    fiobench: image
    deployment: "07"
    subject: local-no-replica
spec:
#  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
  volumeName: fiobench-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiobench-deployment
  namespace: mercado
  labels:
    fiobench: image
    deployment: "07"
    subject: local-no-replica
spec:
  replicas: 1
  selector:
    matchLabels:
      fiobench: image
      deployment: "07"
      subject: local-no-replica
  template:
    metadata:
      labels:
        fiobench: image
        deployment: "07"
        subject: local-no-replica
    spec:
      containers:
      - name: fiobench
        image: ghcr.io/pabloheigvd/tb-fiobench:latest
        command: [ "/bin/sh", "run-all-jobs.sh" ]
#        volumeMounts: # FIXME FailedMount
#          - name: fiobench-storage
#            mountPath: "/data"
      nodeSelector:
        kubernetes.io/hostname: "10.193.72.32"
      volumes:
        - name: fiobench-storage
          persistentVolumeClaim:
            claimName: fiobench-pvc