# inspired from: https://raw.githubusercontent.com/mahaupt/fiobench/master/fiobench.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fiobench-longhorn-pvc
  namespace: mercado
  labels:
    bench: image
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
# inspired from: https://raw.githubusercontent.com/kubernetes/website/main/content/fr/examples/controllers/nginx-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiobench-deployment
  namespace: mercado
  labels:
    fiobench: image
spec:
  replicas: 1
  selector:
    matchLabels:
      fiobench: image
  template:
    metadata:
      labels:
        fiobench: image
    spec:
      containers:
        - name: fiobench
          image: ghcr.io/pabloheigvd/tb-fiobench:0.1.3
          # FIXME  ErrImagePull: rpc error: code = Unknown desc = Error response from daemon:
          #        Get https://ghcr.io/v2/pabloheigvd/tb/manifests/latest: unauthorized
          #  kubectl run fiobench --image ghcr.io/pabloheigvd/tb:latest -l fiobench=run --namespace=mercado
          #  ErrImagePull: rpc error: code = Unknown desc = Error response from daemon:
          #  Get https://ghcr.io/v2/pabloheigvd/tb/manifests/latest: unauthorized
          #

          # clever hack to keep pod running: https://stackoverflow.com/a/40093356
          command: [ "/bin/sh", "run-all-jobs.sh" ]
          volumeMounts:
            - name: test-volume
              mountPath: /data
      volumes:
        - name: test-volume
          persistentVolumeClaim:
            claimName: fiobench-longhorn-pvc
