apiVersion: v1
kind: PersistentVolume
metadata:
  name: fiobench-longhorn-pv
  namespace: mercado
  labels:
    bench: image
    deployment: "03"
    subject: no-replica
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '0'
      staleReplicaTimeout: '2880'
    volumeHandle: existing-longhorn-volume