# "the fio script runs on a different host to the primary host used to create the storage volume"
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fiobench-pv
  namespace: mercado
  labels:
    fiobench: image
    deployment: "07"
    subject: local-volume-with-replica
spec:
  storageClassName: longhorn-static
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '1'
      staleReplicaTimeout: '2880'
      dataLocality: 'disabled' # https://longhorn.io/docs/1.1.2/high-availability/data-locality/#set-the-data-locality-for-individual-volumes-using-a-storageclass
      # the manually created volume has 'data locality' set to 'disabled' AND is attached to node "10.193.72.32"
      # "There may or may not be a replica on the same node as the attached volume (workload)."
      # https://longhorn.io/docs/1.1.2/high-availability/data-locality/#data-locality-settings
      nodeSelector: 'node1'
    volumeHandle: fiobench-vol # refers to volume on node
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - "10.193.72.32"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fiobench-pvc
  namespace: mercado
  labels:
    fiobench: image
    deployment: "07"
    subject: local-volume-with-replica
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
  volumeName: fiobench-pv
  storageClassName: longhorn-static
  selector:
    matchLabels:
      fiobench: image
      deployment: "07"
      subject: local-volume-with-replica
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiobench-deployment
  namespace: mercado
  labels:
    fiobench: image
    deployment: "07"
    subject: local-volume-with-replica
spec:
  replicas: 1
  selector:
    matchLabels:
      fiobench: image
      deployment: "07"
      subject: local-volume-with-replica
  template:
    metadata:
      labels:
        fiobench: image
        deployment: "07"
        subject: local-volume-with-replica
    spec:
      containers:
      - name: fiobench
        image: ghcr.io/pabloheigvd/tb-fiobench:latest
        command: [ "/bin/sh", "run-all-jobs.sh" ]
        volumeMounts:
          - name: fiobench-storage
            mountPath: /data
      nodeSelector:
        kubernetes.io/hostname: "10.193.72.32"
      volumes:
        - name: fiobench-storage
          persistentVolumeClaim:
            claimName: fiobench-pvc
